#!/usr/bin/perl

use strict;
use warnings;
use Data::Dumper;

my $url = shift;

die "Usage: makeport <url>" unless $url;

my $a = process_url( $url );
die Dumper $a;

# get url;
# get comment;
# get version ( if can't extract from url )
# get categories
# get pkgopts
# get wantlib
# get lib_depends
# get configure_style
# build Makefile
# build distinfo
# make build
# drop to patch prompt ( repl with simple cmds for patching files, 
#	dir changing and viewing of error messages from 'make build'
#	cmds:
#		patch ( cp file file.orig - open file in $EDITOR )
#		exit ( quit ) 

sub get_input {
}

sub process_url {
	my $s = shift;


	my @parts = split( '/', $s );
	my $r = {};

	for my $p ( @parts ) {
		if( $p =~ m/((\d+\.){1,}\d+)/ ) {
			$r->{version} = $1;
		}
	}

	# we need to prompt for version here ( assuming we don't have a
	# version from above ) 

	$r->{orig} = $s;
	$r->{file} = $parts[ @parts - 1 ];
	delete $parts[ @parts -1 ];

	$r->{homepage} = join( '/', @parts );

	return $r;
}
