#!/usr/bin/perl

use strict;
use warnings;

my $port = {
	url: "",
	comment: "",
	version: "",
	categories: [],
	pkgopts: [],
	lib_depends: [],
	config_style: ""
};

sub get_input {
}

# get url;
# get comment;
# get version ( if can't extract from url )
# get categories
# get pkgopts
# get wantlib
# get lib_depends
# get configure_style
# build Makefile
# build distinfo
# make build
# drop to patch prompt ( repl with simple cmds for patching files, 
#	dir changing and viewing of error messages from 'make build'
#	cmds:
#		patch ( cp file file.orig - open file in $EDITOR )
#		exit ( quit ) 
